#script parameters
model_id: "meta-llama/Meta-Llama-3-70b"
dataset_path: "data"
max_seq_length: 3072
output_dir: "./llama-3-70b-hf-no-robot"
report_to: "tensor_board"
learning_rate: 0.0002
lr_scheduler_type: "constant"
num_train_epochs: 3
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
gradient_accumulation_steps: 2
optim: adamw_torch
logging_steps: 10
save_strategy: epoch
evaluation_strategy: epoch
max_grad_norm: 0.3
warmpup_ratio: 0.03
bf16: true
tf32: true
gradient_checkpointing: true
fsdp: "full_shared_auto_wrap_offload"
fsdp_config:
  backward_prefetch: "backward_pre"
  forward_prefetch: "false"
  use_orig_params: "false"